# Generated by Django 2.2.5 on 2019-09-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Musica', models.CharField(max_length=255, verbose_name='Nome_Musica')),
                ('Artista', models.CharField(max_length=50, verbose_name='Artista')),
                ('Genero', models.CharField(max_length=50, verbose_name='Genero')),
                ('Link_Musica', models.CharField(max_length=50, verbose_name='Link_Musica')),
            ],
        ),
    ]
